from __future__ import annotations

import json
import os
import shlex
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

SUPPORTED_SOFTWARE = {
    "hypermesh": "HyperMesh",
    "ansys_mapdl": "ANSYS MAPDL / PyMAPDL",
    "ansys_fluent": "ANSYS Fluent / PyFluent",
    "marc": "MSC Marc/Mentat",
    "flow3d": "FLOW-3D",
}


def execution_status() -> dict[str, Any]:
    enabled = os.getenv("SIMULATION_EXECUTION_ENABLED", "false").lower() in {"1", "true", "yes", "on"}
    adapters = {}
    for key, label in SUPPORTED_SOFTWARE.items():
        command = os.getenv(f"SIM_{key.upper()}_COMMAND", "").strip()
        adapters[key] = {"label": label, "configured": bool(command), "command_env": f"SIM_{key.upper()}_COMMAND"}
    return {"execution_enabled": enabled, "adapters": adapters}


def _common_readme(name: str, software: str, parameters: dict[str, Any]) -> str:
    return f"""# {name}\n\n目标软件：{SUPPORTED_SOFTWARE[software]}\n\n本目录由 EnerTri 生成，用于焊接过程数值仿真的前处理和批处理集成。\n\n## 使用原则\n\n1. 在真实求解前核对单位制、材料热物性、热源模型、边界条件、网格独立性与时间步独立性。\n2. 用热循环、熔池形貌、变形或残余应力实验数据进行标定和验证。\n3. 商业软件许可证、可执行文件路径和命令行参数由部署管理员配置。\n4. 自动生成内容是可编辑模板，不替代 CAE 工程师审查。\n\n## 输入参数\n\n```json\n{json.dumps(parameters, ensure_ascii=False, indent=2)}\n```\n"""


def _heat_source_comments(p: dict[str, Any]) -> str:
    current = p.get("current_a", 220)
    voltage = p.get("voltage_v", 24)
    efficiency = p.get("efficiency", 0.8)
    speed = p.get("travel_speed_mm_s", 5)
    power = round(float(current) * float(voltage) * float(efficiency), 3)
    line_energy = round(power / max(float(speed), 0.001), 3)
    return f"电流={current} A, 电压={voltage} V, 热效率={efficiency}, 速度={speed} mm/s, 有效功率={power} W, 线能量={line_energy} J/mm"


def _hypermesh_script(p: dict[str, Any]) -> str:
    size = p.get("mesh_size_mm", 2.0)
    return f"""# HyperMesh Tcl template generated by EnerTri\n# {_heat_source_comments(p)}\n# The exact commands vary by HyperMesh release and solver profile.\n*clearmark all 1\n# TODO: import geometry\n# *feinputwithdata2 \"#detect\" \"model.step\" 0 0 0 0 0 1 0 1 0\n# TODO: set solver profile, material, properties and weld path\n# Suggested nominal mesh size: {size} mm\n# TODO: create fine mesh around fusion zone and HAZ, then export solver deck\nputs \"EnerTri HyperMesh template loaded. Complete geometry-specific commands before execution.\"\n"""


def _mapdl_script(p: dict[str, Any]) -> str:
    length = float(p.get("length_mm", 100))
    width = float(p.get("width_mm", 50))
    thickness = float(p.get("thickness_mm", 8))
    mesh = float(p.get("mesh_size_mm", 2))
    return f"""! ANSYS MAPDL welding thermal template generated by EnerTri\n! {_heat_source_comments(p)}\n/PREP7\nET,1,SOLID70\n! Geometry placeholder: plate block in mm\nBLOCK,0,{length},0,{width},0,{thickness}\nESIZE,{mesh}\nVMESH,ALL\n! TODO: define temperature-dependent KXX, C, DENS and enthalpy/latent heat\n! TODO: define moving Goldak double-ellipsoid or equivalent volumetric heat source\n! TODO: apply convection/radiation boundaries and birth-death sequence\nFINISH\n/SOLU\nANTYPE,TRANS\nTRNOPT,FULL\n! TODO: time stepping and heat source loop\nFINISH\n/POST1\n! TODO: export temperature histories for validation\n"""


def _fluent_journal(p: dict[str, Any]) -> str:
    return f"""; ANSYS Fluent welding flow/heat-transfer journal template\n; {_heat_source_comments(p)}\n; TODO: read mesh and verify units\n; /file/read-mesh model.msh.h5\n; TODO: enable energy, melting/solidification and appropriate turbulence/laminar model\n; TODO: define material properties, latent heat, mushy-zone constant, surface tension and buoyancy\n; TODO: compile/load UDF for moving heat source and optional Marangoni force\n; TODO: initialize and run transient time steps\n; /file/write-case-data result.cas.h5\n"""


def _marc_proc(p: dict[str, Any]) -> str:
    return f"""# MSC Marc/Mentat procedure template generated by EnerTri\n# {_heat_source_comments(p)}\n# TODO: import/create geometry, define thermal-mechanical coupled analysis\n# TODO: assign temperature-dependent material properties and phase/transformation model\n# TODO: define moving heat flux, convection/radiation and contact/restraints\n# TODO: create adaptive time steps and output requests\n# Execute using the Marc/Mentat batch command configured by the administrator.\n"""


def _flow3d_config(p: dict[str, Any]) -> str:
    config = {
        "project": p.get("project", "enertri_welding"),
        "units": "SI-mm-s-C",
        "process": p.get("process", "fusion_welding"),
        "heat_source": {
            "model": p.get("heat_source_model", "gaussian_or_user_defined"),
            "current_a": p.get("current_a"),
            "voltage_v": p.get("voltage_v"),
            "efficiency": p.get("efficiency"),
            "travel_speed_mm_s": p.get("travel_speed_mm_s"),
        },
        "geometry": p.get("geometry", {}),
        "material": p.get("material", {}),
        "boundary_conditions": p.get("boundary_conditions", {}),
        "notes": ["Map these fields to the FLOW-3D Welding project schema for the installed release.", "Validate free-surface, recoil pressure, surface tension and phase-change settings."],
    }
    return json.dumps(config, ensure_ascii=False, indent=2)


def create_simulation_package(workdir: Path, name: str, software: str, parameters: dict[str, Any]) -> Path:
    if software not in SUPPORTED_SOFTWARE:
        raise ValueError("unsupported simulation software")
    workdir.mkdir(parents=True, exist_ok=True)
    (workdir / "README.md").write_text(_common_readme(name, software, parameters), encoding="utf-8")
    (workdir / "parameters.json").write_text(json.dumps(parameters, ensure_ascii=False, indent=2), encoding="utf-8")
    if software == "hypermesh":
        (workdir / "enertri_hypermesh.tcl").write_text(_hypermesh_script(parameters), encoding="utf-8")
        input_file = "enertri_hypermesh.tcl"
    elif software == "ansys_mapdl":
        (workdir / "welding_thermal.dat").write_text(_mapdl_script(parameters), encoding="utf-8")
        input_file = "welding_thermal.dat"
    elif software == "ansys_fluent":
        (workdir / "welding_fluent.jou").write_text(_fluent_journal(parameters), encoding="utf-8")
        input_file = "welding_fluent.jou"
    elif software == "marc":
        (workdir / "welding_marc.proc").write_text(_marc_proc(parameters), encoding="utf-8")
        input_file = "welding_marc.proc"
    else:
        (workdir / "flow3d_project.json").write_text(_flow3d_config(parameters), encoding="utf-8")
        input_file = "flow3d_project.json"
    manifest = {"name": name, "software": software, "input_file": input_file, "parameters": parameters}
    (workdir / "manifest.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")
    archive = Path(shutil.make_archive(str(workdir), "zip", root_dir=workdir))
    return archive


def launch_simulation(job_id: int, software: str, workdir: Path) -> int:
    status = execution_status()
    if not status["execution_enabled"]:
        raise RuntimeError("仿真执行开关未开启；当前仅生成可下载输入包")
    template = os.getenv(f"SIM_{software.upper()}_COMMAND", "").strip()
    if not template:
        raise RuntimeError(f"未配置 SIM_{software.upper()}_COMMAND")
    runner = Path(__file__).with_name("simulation_runner.py")
    process = subprocess.Popen(
        [sys.executable, str(runner), str(job_id), software, str(workdir), template],
        cwd=str(workdir),
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        close_fds=os.name != "nt",
    )
    return int(process.pid)


def refresh_result(workdir: Path) -> dict[str, Any] | None:
    result_path = workdir / "simulation_result.json"
    if not result_path.exists():
        return None
    try:
        return json.loads(result_path.read_text(encoding="utf-8"))
    except Exception:
        return {"status": "failed", "message": "结果文件无法解析"}
